#This workflow checks for any merge conflicts, if not it will merge branch to main branch

name: Merge to main if there are no merge conflicts

on:
  push:
    branches: [ main ]

jobs:
  merge-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Check for conflicts
        run: |
          if [[ -n $(git diff --name-only --diff-filter=U) ]]; then
            echo "Merge conflict occured, resolve the conflict before merging"
            git merge --abort
            exit 1
          else
            echo "No merge conflicts"
          fi

      - name: Merge branch to main
        run: |
          git merge --no-commit --no-ff ${{ github.event.ref }}
